project:
  type: website
  
website:
  title: "EXST 7151: Bayesian Data Analysis"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: lectures/index.qmd
        text: Lecture notes
knitr:
  opts_chunk: 
    collapse: true
    fig.show: "hold"
editor_options: 
  chunk_output_type: console

number-sections: true
format:
  html:
    theme: flatly
    toc: true
    linkcolor: "#009E60"
    embed-resources: true
